POST /api/accountants/filter
Host: localhost:8080
#Host: companies-house-frontend-api-rmfuc.ondigitalocean.app
Content-Type: application/json

[
  {
    "category": "production software",
    "comparison": "begins with",
    "values": [
      "CCH Software"
    ],
    "type": "string"
  }
]

###


GET /api/events/03511297
Host: localhost:8080
#Host: companies-house-frontend-api-rmfuc.ondigitalocean.app
Accept: application/json

###

