POST /api/accountants
#Host: localhost:8080
Host: companies-house-frontend-api-rmfuc.ondigitalocean.app
Content-Type: application/json

[
  {
    "category": "software",
    "comparison": "equals",
    "value": "CCH Software"
  }
]

###


GET /api/events/03511297
Host: localhost:8080
#Host: companies-house-frontend-api-rmfuc.ondigitalocean.app
Accept: application/json

###

