POST /api/accountants/filter
Host: localhost:8080
#Host: companies-house-frontend-api-rmfuc.ondigitalocean.app
Content-Type: application/json

[
  {
    "category": "location",
    "comparison": "includes",
    "values": [
      "TauNtOn"
    ],
    "type": "string"
  },
  {
    "category": "number of clients",
    "comparison": "between",
    "min": 5,
    "max": 200,
    "type": "number"
  },
  {
    "category": "name",
    "comparison": "begins with",
    "values": [
      "som"
    ],
    "type": "string"
  }
]

###
POST /api/companies/filter
Host: localhost:8080
#Host: companies-house-frontend-api-rmfuc.ondigitalocean.app
Content-Type: application/json

[
  {
    "category": "location",
    "comparison": "includes",
    "values": [
      "TauNtOn"
    ],
    "type": "string"
  },
  {
    "category": "name",
    "comparison": "begins with",
    "values": [
      "som"
    ],
    "type": "string"
  }
]

###


GET /api/events/03511297
#Host: localhost:8080
Host: companies-house-frontend-api-rmfuc.ondigitalocean.app
Accept: application/json
Content-Type: application/json

###

GET /api/accountants/filter
Host: companies-house-frontend-api-rmfuc.ondigitalocean.app
Accept: application/json
Content-Type: application/json

{
  "body": "Hello, I am filter"
}

###
GET /api/search/book
Host: localhost:8080


###
POST https://carbonnowsh.herokuapp.com/?code=select * from companies&language=sql
content-type: application/json

{
  "code": "select * from companies",
  "language": "sql",
  "theme": "dracula"
}
