// FILE GENERATED BY generator.js
import { IFilterOption, INumberFilter } from '../../../types/IFilters'
import { IMinorQuery } from '../../../types/IQueries'

export const filterCompaniesByChangeOfOwnership: (filter: INumberFilter) => IMinorQuery = (filter) => {
  //todo: add date range constraints
  // - add the values[] of the event to the database to check for the same person, and the actual date
  // - the query is too slow, so speed it up somehow
  const query = `
      SELECT DISTINCT company_number FROM filing_events
        WHERE description_code = 'notification-of-a-person-with-significant-control'
        AND filing_date BETWEEN CURRENT_DATE - (?::TEXT||' days')::INTERVAL
                AND CURRENT_DATE - (?::TEXT||' days')::INTERVAL
INTERSECT 
      SELECT DISTINCT company_number FROM filing_events
        WHERE description_code = 'cessation-of-a-person-with-significant-control'
        AND filing_date BETWEEN CURRENT_DATE - (?::TEXT||' days')::INTERVAL
                AND CURRENT_DATE - (?::TEXT||' days')::INTERVAL
  `

  return {
    query,
    value: [filter.max, filter.min, filter.max, filter.min]
  }
}

export const filterCompaniesByChangeOfOwnershipMetadata: IFilterOption = {
  category: 'change of ownership',
  possibleComparisons: ['is between'],
  valueType: 'number'
}
